from pydantic import BaseModel, Field


class ComparableListing(BaseModel):
    platform: str
    title: str
    price: float | None = None
    url: str | None = None
    notes: str = ""


class PlatformEstimate(BaseModel):
    platform: str
    price: float


class ItemResearchModelOutput(BaseModel):
    """Research and pricing output — name and description are generated separately."""

    category: str = Field(
        description="Exact category name chosen from the seller's provided category list."
    )
    condition_suggestion: str = Field(
        description="One of: new, pre-owned:excellent, pre-owned:good, pre-owned:fair, pre-owned:damaged."
    )
    projected_sale_price: float = Field(description="Estimated resale price in USD.")
    starting_bid_suggestion: float = Field(description="Suggested auction starting bid in USD.")
    platform_price_estimates: list[PlatformEstimate] = Field(
        default_factory=list,
        description="Per-platform price estimates for ebay, etsy, whatnot when justified.",
    )
    comparable_listings: list[ComparableListing] = Field(
        default_factory=list,
        description="Up to 5 comparable listings or dealer references with URLs from web search.",
    )
    confidence: float = Field(description="Confidence score from 0 to 1.")
    reasoning: str = Field(
        description="Brief 1-2 sentence plain-text price summary. No markdown or URLs."
    )


class ItemDescriptionModelOutput(BaseModel):
    """Short listing copy generated by a lightweight model."""

    name: str = Field(
        max_length=40,
        description=(
            "Brief inventory phrase, 2-5 words and under 40 characters. "
            "Not a full marketplace title."
        ),
    )
    description: str = Field(
        max_length=250,
        description=(
            "Very short item summary in 1-2 sentences: what it is plus one key detail "
            "(era, maker, materials, or condition). No paragraphs, bullets, or headers."
        ),
    )


class ItemAnalysisModelOutput(BaseModel):
    """Full analysis combining research and description."""

    name: str
    category: str
    description: str
    condition_suggestion: str
    projected_sale_price: float
    starting_bid_suggestion: float
    platform_price_estimates: list[PlatformEstimate] = Field(default_factory=list)
    comparable_listings: list[ComparableListing] = Field(default_factory=list)
    confidence: float
    reasoning: str

    @classmethod
    def from_parts(
        cls,
        research: ItemResearchModelOutput,
        description: ItemDescriptionModelOutput,
    ) -> "ItemAnalysisModelOutput":
        return cls(
            name=description.name,
            category=research.category,
            description=description.description,
            condition_suggestion=research.condition_suggestion,
            projected_sale_price=research.projected_sale_price,
            starting_bid_suggestion=research.starting_bid_suggestion,
            platform_price_estimates=research.platform_price_estimates,
            comparable_listings=research.comparable_listings,
            confidence=research.confidence,
            reasoning=research.reasoning,
        )

    def to_response(self) -> "ItemAnalysisResponse":
        return ItemAnalysisResponse(
            name=self.name,
            category=self.category,
            description=self.description,
            condition_suggestion=self.condition_suggestion,
            projected_sale_price=self.projected_sale_price,
            starting_bid_suggestion=self.starting_bid_suggestion,
            platform_estimates={estimate.platform: estimate.price for estimate in self.platform_price_estimates},
            comparable_listings=self.comparable_listings,
            confidence=self.confidence,
            reasoning=self.reasoning,
        )


class ItemAnalysisResponse(BaseModel):
    name: str
    category: str
    description: str
    condition_suggestion: str
    projected_sale_price: float = Field(ge=0)
    starting_bid_suggestion: float = Field(ge=0)
    platform_estimates: dict[str, float] = Field(default_factory=dict)
    comparable_listings: list[ComparableListing] = Field(default_factory=list)
    confidence: float = Field(ge=0, le=1)
    reasoning: str
