/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInventoryRouteRouteImport } from './routes/_authenticated/inventory/route'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedInventoryNewRouteImport } from './routes/_authenticated/inventory/new'
import { Route as AuthenticatedInventoryItemIdRouteImport } from './routes/_authenticated/inventory/$itemId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRouteRoute =
  AuthenticatedInventoryRouteRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInventoryRouteRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryNewRoute =
  AuthenticatedInventoryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInventoryRouteRoute,
  } as any)
const AuthenticatedInventoryItemIdRoute =
  AuthenticatedInventoryItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedInventoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inventory': typeof AuthenticatedInventoryRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/inventory/$itemId': typeof AuthenticatedInventoryItemIdRoute
  '/_authenticated/inventory/new': typeof AuthenticatedInventoryNewRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventory'
    | '/dashboard'
    | '/profile'
    | '/inventory/$itemId'
    | '/inventory/new'
    | '/categories/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/profile'
    | '/inventory/$itemId'
    | '/inventory/new'
    | '/categories'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/inventory'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/inventory/$itemId'
    | '/_authenticated/inventory/new'
    | '/_authenticated/categories/'
    | '/_authenticated/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedInventoryRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/new': {
      id: '/_authenticated/inventory/new'
      path: '/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof AuthenticatedInventoryNewRouteImport
      parentRoute: typeof AuthenticatedInventoryRouteRoute
    }
    '/_authenticated/inventory/$itemId': {
      id: '/_authenticated/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof AuthenticatedInventoryItemIdRouteImport
      parentRoute: typeof AuthenticatedInventoryRouteRoute
    }
  }
}

interface AuthenticatedInventoryRouteRouteChildren {
  AuthenticatedInventoryItemIdRoute: typeof AuthenticatedInventoryItemIdRoute
  AuthenticatedInventoryNewRoute: typeof AuthenticatedInventoryNewRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedInventoryRouteRouteChildren: AuthenticatedInventoryRouteRouteChildren =
  {
    AuthenticatedInventoryItemIdRoute: AuthenticatedInventoryItemIdRoute,
    AuthenticatedInventoryNewRoute: AuthenticatedInventoryNewRoute,
    AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  }

const AuthenticatedInventoryRouteRouteWithChildren =
  AuthenticatedInventoryRouteRoute._addFileChildren(
    AuthenticatedInventoryRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedInventoryRouteRoute: typeof AuthenticatedInventoryRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInventoryRouteRoute:
    AuthenticatedInventoryRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
